# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go (6639734e-66ce-4540-adc9-62b2465bcc4c)'
    backendAzureRmResourceGroupName: 'aks'
    backendAzureRmStorageAccountName: 'stgaks29'
    backendAzureRmContainerName: 'akstf'
    backendAzureRmKey: 'aks.tfstate'

- task: TerraformTaskV3@3
  displayName: 'Terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (6639734e-66ce-4540-adc9-62b2465bcc4c)'

- task: TerraformTaskV3@3
  displayName: 'Terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'Pay-As-You-Go (6639734e-66ce-4540-adc9-62b2465bcc4c)'